### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [compute-io/zeros#2]
Address compute-io/todo#113.

**Comment by Planeshifter** [comment]
Two minor remarks:
1. in `index.js`, the documentation for the return statement is 

```
* @returns {Number[]|Int8Array|Uint8Array|Uint8ClampedArray|Int16Array|Uint16Array|Int32Array|Uint32Array|Float32Array|Float64Array|Matrix} zeros
```

Should we replace `Number[]` with `Array` as most of the time one will create not a number array, but an array-of-arrays?
1.  What about renaming the variable `isArray` - which appears in `compile.js` and `index.js` - to something like `isPosIntArray`?

**Comment by kgryte** [comment]
Re: output data type. You are correct. I added `Array` to the list.

Re: `isArray`. I chose `isArray` as its usage after validation strictly relates to whether `dims` is an `array` and not whether the `array` contains `integers`. And due to the file being not so long that a reader would forget that `dims` must be an `array` of positive `integers`. My main criteria for naming is
- is the name sufficiently self descriptive that a reader has enough of a hint to maintain a mental mapping of all variables being used within a view?
- is the file short/simple enough that variable names are less important? i.e., can I get by with naming an input value `x`? (note: `x`, `y`, etc. are sometimes used to denote values which may take on multiple types, like matrices, typed-arrays, arrays, etc., not just for brevity.)
- is the name as short as possible, without being a indecipherable acronym that itself requires a mental map? (longer names take up more memory)
- is the name consistent (or consistent enough) with naming conventions? e.g., camel-casing conventions and when those are broken. e.g., `ndims` versus `nDims` (I went back through the `matrix` code to check.)
- what makes sense to me? This criterion undoubtedly has more influence than I care to admit. 

If the file were longer and whether the `array` contained positive `integers` was essential to understanding the variable's usage context and additional code, then I agree: the name should be more self-descriptive. Otherwise, I am fine with saving some memory and being descriptive enough.

Sound reasonable?

**Comment by kgryte** [comment]
@Planeshifter: split into separate files. Worth another look over to ensure all is okay. Thanks!

**Comment by Planeshifter** [comment]
Published `v0.0.0` to npm. Do you want to take one last look and then release version `v1.0.0`?

**Comment by kgryte** [comment]
@Planeshifter Yep. Looks fine. Go ahead and release `v1.0.0`.

**Comment by Planeshifter** [comment]
Done.
