### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by vegetableman** [compute-io/zeros#3]
This package is not yet published to npm. But the readme says otherwise. Plans to publish it? Thanks.

**Comment by kgryte** [comment]
@vegetableman Thanks for the ping. Publishing this module is dependent on compute-io/zeros#2. Once given the final sign-off, this module will be published to NPM. Should be done shortly.

Pinging: @Planeshifter . We also have a `development` branch. Do we need to cherry pick anything from there into `master`?

**Comment by Planeshifter** [comment]
The package has now landed on npm, so I am closing this issue.
